//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_for_seminar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson_Content
    {
        public int ID { get; set; }
        public string Image1_C { get; set; }
        public string Image2_S { get; set; }
        public string Image3 { get; set; }
        public string Voice { get; set; }
        public string name { get; set; }
        public Nullable<int> LessonID { get; set; }
        public string video { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
