//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_for_seminar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KidsKingdomEntities3 : DbContext
    {
        public KidsKingdomEntities3()
            : base("name=KidsKingdomEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kid> Kids { get; set; }
        public virtual DbSet<Kid_level_practice> Kid_level_practice { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Lesson_Content> Lesson_Content { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Practice> Practices { get; set; }
        public virtual DbSet<Practice_content> Practice_content { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
